### ISSUE TITLE
add Java 9 support

### ISSUE THREAD

**Issue by FrVaBe** [mojohaus/aspectj-maven-plugin#24] opened 2017-03-07 14:32 UTC
When building a project that makes use of the aspectj-maven-plugin:1.9 with a pre release version of Java 9 the following execption occures:

> [ERROR] Failed to execute goal org.codehaus.mojo:aspectj-maven-plugin:1.9:compile (default) on project foobar: Execution default of goal org.codehaus.mojo:aspectj-maven-plugin:1.9:compile failed: Plugin org.codehaus.mojo:aspectj-maven-plugin:1.9 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:9-ea at specified path C:\Program Files\Java\jdk-9/../lib/tools.jar -> [Help 1]

I already upgraded the aspectjtools to version 1.9.0.BETA-5 (which should support Java 9) but that does not fix the issue.

The use of the tools.jar is mentioned in the pom.xml of the aspectj-maven-plugin - thus it is probably the plugin which needs some changes to (also) support Java 9.

**Comment by cmuramoto** [comment] 2017-04-30 09:15
Hello @FrVaBe , version 1.11 seems to be working, with a minor hack on build 9-ea+164.

The plugin currently looks for jrt-fs.jar on $JAVA_HOME insteand of $JAVA_HOME/lib. Just make a copy of this jar and voila.

**Comment by FrVaBe** [comment] 2017-05-02 07:29
@cmuramoto Thanks for the tip but I tend to wait for a solution that will not depend on finding files in the file system.

**Comment by unltd** [comment] 2017-09-25 14:19
Now the Java 9 is here! It'd be perfect to have the 1.11 released.

**Comment by davidkarlsen** [comment] 2017-09-25 19:35
I believe we need aspectj 1.9 for that

**Comment by ishanthi** [comment] 2017-11-07 17:01
Hello, When is the expected to be released?

**Comment by avdyk** [comment] 2017-11-28 15:44
https://www.eclipse.org/aspectj/ 1.9.0.RC2 was available on Nov 9

**Comment by MarkAtAllpliant** [comment] 2018-01-10 15:29
Still seeing the same issue. I am using the latest version of plugin and RC2 of AspectJ:

`      <plugin>
         <groupId>org.codehaus.mojo</groupId>
          <artifactId>aspectj-maven-plugin</artifactId>
          <version>1.10</version>
          <configuration>       
          <encoding>${project.build.sourceEncoding}</encoding>
          <complianceLevel>1.9</complianceLevel>
          <showWeaveInfo>true</showWeaveInfo>
          <XnoInline>true</XnoInline>
        <aspectLibraries>
            <aspectLibrary>
              <groupId>org.me</groupId>
              <artifactId>tracing</artifactId>
            </aspectLibrary>
          </aspectLibraries>		  
          </configuration>
          <executions>
            <execution>
              <goals>
                <goal>compile</goal>
                  <goal>test-compile</goal>
              </goals>
            </execution>
          </executions>
          <dependencies>
           <dependency>
           <groupId>org.aspectj</groupId>
           <artifactId>aspectjrt</artifactId>
           <version>1.9.0.RC2</version>
          </dependency> 
          <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjtools</artifactId>
            <version>1.9.0.RC2</version>
           </dependency>
           </dependencies>
      </plugin>
    </plugins>`

I am getting the error: 

>  Execution default of goal org.codehaus.mojo:aspectj-maven-plugin:1.10:compile failed: Plugin org.codehaus.mojo:aspectj-maven-plugin:1.10 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:9.0.1 at specified path C:\Program Files\Java\jdk-9.0.1/../lib/tools.jar ->

**Comment by megglos** [comment] 2018-02-03 20:51
Ran into the same issue and from my perspective the problem ist that the profile for this <1.9 JDK only jar is active by default but should only be active if the jar exists.

Please check this PR https://github.com/mojohaus/aspectj-maven-plugin/pull/35 if it resolves the issue for you case as well.

**Comment by davidkarlsen** [comment] 2018-02-04 20:00
Can you try the latest 1.11.1-SNAPSHOT ? I merged the PR.

**Comment by turbanoff** [comment] 2018-02-11 01:22
I tried to run version from repo. Got this strange error on java 9
> [main] [ERROR] Failed to execute goal org.codehaus.mojo:aspectj-maven-plugin:1.11.0_2018_02_11:compile (default) on project dxAuthServer: AJC compiler errors:
[main] [ERROR] error can't determine superclass of missing type java.lang.Object
[main] [ERROR] when batch building BuildConfig[null] #Files=57 AopXmls=#0
[main] [ERROR]  [Xlint:cantFindType]
[main] [ERROR] error can't determine superclass of missing type java.lang.Object
[main] [ERROR] when batch building BuildConfig[null] #Files=57 AopXmls=#0
[main] [ERROR]  [Xlint:cantFindType]
[main] [ERROR] error can't determine superclass of missing type java.lang.Object
[main] [ERROR] when batch building BuildConfig[null] #Files=57 AopXmls=#0
[main] [ERROR]  [Xlint:cantFindType]
[main] [ERROR] error can't determine superclass of missing type java.lang.Object
[main] [ERROR] when batch building BuildConfig[null] #Files=57 AopXmls=#0
[main] [ERROR]  [Xlint:cantFindType]
[main] [ERROR] error can't determine superclass of missing type java.lang.Object
[main] [ERROR] when batch building BuildConfig[null] #Files=57 AopXmls=#0
[main] [ERROR]  [Xlint:cantFindType]
[main] [ERROR] error can't determine superclass of missing type java.lang.Object
[main] [ERROR] when batch building BuildConfig[null] #Files=57 AopXmls=#0
[main] [ERROR]  [Xlint:cantFindType]
[main] [ERROR] error can't determine superclass of missing type java.lang.Object
[main] [ERROR] when batch building BuildConfig[null] #Files=57 AopXmls=#0
[main] [ERROR]  [Xlint:cantFindType]
[main] [ERROR] error can't determine superclass of missing type java.lang.Object
[main] [ERROR] when batch building BuildConfig[null] #Files=57 AopXmls=#0
[main] [ERROR]  [Xlint:cantFindType]
[main] [ERROR] error can't determine superclass of missing type java.lang.Object
[main] [ERROR] when batch building BuildConfig[null] #Files=57 AopXmls=#0
[main] [ERROR]  [Xlint:cantFindType]
[main] [ERROR] error can't determine superclass of missing type java.lang.Object
[main] [ERROR] when batch building BuildConfig[null] #Files=57 AopXmls=#0
[main] [ERROR]  [Xlint:cantFindType]
[main] [ERROR] error can't determine superclass of missing type java.lang.Object
[main] [ERROR] when batch building BuildConfig[null] #Files=57 AopXmls=#0
[main] [ERROR]  [Xlint:cantFindType]
[main] [ERROR] error can't determine superclass of missing type java.lang.Object
[main] [ERROR] when batch building BuildConfig[null] #Files=57 AopXmls=#0
[main] [ERROR]  [Xlint:cantFindType]
[main] [ERROR] error can't determine superclass of missing type java.lang.Object
[main] [ERROR] when batch building BuildConfig[null] #Files=57 AopXmls=#0
[main] [ERROR]  [Xlint:cantFindType]

**Comment by davidkarlsen** [comment] 2018-02-11 12:40
can you maybe run it with -X to reveal more detail?

**Comment by turbanoff** [comment] 2018-02-11 12:57
Debug log:
>[main] [INFO] --- aspectj-maven-plugin:1.11.0_2018_02_11:compile (default) @ configServer ---
[main] [DEBUG] Configuring mojo org.codehaus.mojo:aspectj-maven-plugin:1.11.0_2018_02_11:compile from plugin realm ClassRealm[plugin>org.codehaus.mojo:aspectj-maven-plugin:1.11.0_2018_02_11, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@73a8dfcc]
[main] [DEBUG] Configuring mojo 'org.codehaus.mojo:aspectj-maven-plugin:1.11.0_2018_02_11:compile' with basic configurator -->
[main] [DEBUG]   (s) Xajruntimetarget = 1.5
[main] [DEBUG]   (s) argumentFileName = builddef.lst
[main] [DEBUG]   (f) aspectDirectory = src/main/aspect
[main] [DEBUG]   (s) groupId = org.springframework
[main] [DEBUG]   (s) artifactId = spring-aspects
[main] [DEBUG]   (s) groupId = some
[main] [DEBUG]   (s) artifactId = serverFoundation
[main] [DEBUG]   (f) aspectLibraries = [org.springframework:spring-aspects, some:serverFoundation]
[main] [DEBUG]   (f) basedir = D:\proj\server\configServer
[main] [DEBUG]   (s) complianceLevel = 1.8
[main] [DEBUG]   (s) encoding = UTF-8
[main] [DEBUG]   (f) forceAjcCompile = false
[main] [DEBUG]   (f) generatedSourcesDirectory = D:\proj\server\configServer\target\generated-sources\aspectj-maven-plugin
[main] [DEBUG]   (f) outputDirectory = D:\proj\server\configServer\target\classes
[main] [DEBUG]   (f) project = MavenProject: some:configServer:168-SNAPSHOT @ D:\proj\server\configServer\pom.xml
[main] [DEBUG]   (s) showWeaveInfo = true
[main] [DEBUG]   (f) skip = false
[main] [DEBUG]   (s) source = 1.8
[main] [DEBUG]   (s) target = 1.8
[main] [DEBUG]   (f) testAspectDirectory = src/test/aspect
[main] [DEBUG] -- end configuration --
[main] [DEBUG] Not adding non-existent or already added aspectSourcePathDir [D:\proj\server\configServer\src\main\aspect] to compileSourceRoots.
[main] [DEBUG] Not adding non-existent or already added testAspectSourcePathDir [D:\proj\server\configServer\src\test\aspect] to testCompileSourceRoots.
[main] [DEBUG] Adding -aspectpath: C:\Users\turbanov\.m2\repository\org\springframework\spring-aspects\4.3.8.RELEASE\spring-aspects-4.3.8.RELEASE.jar;D:\proj\server\serverFoundation\target\classes
[main] [DEBUG] Running : ajc -Xajruntimetarget:1.5 -1.8 -encoding UTF-8 -showWeaveInfo -source 1.8 -target 1.8 -classpath D:\proj\server\serverFoundation\target\classes;D:\proj\server\dxAuthServer\target\classes;D:\proj\common\connectivity\target\classes;D:\proj\common\common-utils\target\classes;C:\Users\turbanov\.m2\repository\org\quartz-scheduler\quartz\2.2.1\quartz-2.2.1.jar;C:\Users\turbanov\.m2\repository\org\jhiccup\jHiccup\2.0.6\jHiccup-2.0.6.jar;C:\Users\turbanov\.m2\repository\com\devexperts\qd\qds\3.255\qds-3.255.jar;C:\Users\turbanov\.m2\repository\com\devexperts\qd\dxlib\3.255\dxlib-3.255.jar;C:\Users\turbanov\.m2\repository\com\devexperts\qd\dxfeed-api\3.255\dxfeed-api-3.255.jar;D:\proj\dxAuth\dxauth-api\target\classes;D:\proj\dxcore-api-interfaces\target\classes;D:\proj\domain-descriptors-model\domain-descriptors-model-api\target\classes;D:\proj\Services\dxConfig\dxconfig-api\target\classes;D:\proj\API\target\classes;D:\proj\domain-descriptors-model\metrics-calculation-context-domain-descriptors\target\classes;D:\proj\calculators-api\target\classes;C:\Users\turbanov\.m2\repository\com\google\guava\guava\20.0\guava-20.0.jar;C:\Users\turbanov\.m2\repository\com\google\code\gson\gson\2.1\gson-2.1.jar;D:\proj\common\common-api\target\classes;C:\Users\turbanov\.m2\repository\com\google\code\findbugs\jsr305\3.0.1\jsr305-3.0.1.jar;D:\proj\domain-descriptors-model\domain-descriptors-model-impl\target\classes;D:\proj\common\basic-utils\target\classes;D:\proj\common\common-utils-dao\target\classes;D:\proj\common\common-json\target\classes;D:\proj\dxcore-impl\target\classes;D:\proj\dxAuth\dxauth-impl\target\classes;C:\Users\turbanov\.m2\repository\com\fasterxml\jackson\jaxrs\jackson-jaxrs-json-provider\2.5.4\jackson-jaxrs-json-provider-2.5.4.jar;C:\Users\turbanov\.m2\repository\com\fasterxml\jackson\jaxrs\jackson-jaxrs-base\2.5.4\jackson-jaxrs-base-2.5.4.jar;C:\Users\turbanov\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.5.4\jackson-core-2.5.4.jar;C:\Users\turbanov\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.5.4\jackson-databind-2.5.4.jar;C:\Users\turbanov\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.5.4\jackson-annotations-2.5.4.jar;C:\Users\turbanov\.m2\repository\com\fasterxml\jackson\module\jackson-module-jaxb-annotations\2.5.4\jackson-module-jaxb-annotations-2.5.4.jar;D:\proj\Services\dxConfig\dxconfig-impl\target\classes;C:\Users\turbanov\.m2\repository\com\devexperts\qd\mars\3.255\mars-3.255.jar;C:\Users\turbanov\.m2\repository\org\javasimon\javasimon-core\4.1.1\javasimon-core-4.1.1.jar;D:\proj\server\server-api\target\classes;D:\proj\dxcore-spring\target\classes;C:\Users\turbanov\.m2\repository\org\springframework\spring-aop\4.3.8.RELEASE\spring-aop-4.3.8.RELEASE.jar;C:\Users\turbanov\.m2\repository\org\springframework\spring-aspects\4.3.8.RELEASE\spring-aspects-4.3.8.RELEASE.jar;C:\Users\turbanov\.m2\repository\org\springframework\spring-beans\4.3.8.RELEASE\spring-beans-4.3.8.RELEASE.jar;C:\Users\turbanov\.m2\repository\org\springframework\spring-context\4.3.8.RELEASE\spring-context-4.3.8.RELEASE.jar;C:\Users\turbanov\.m2\repository\org\springframework\spring-context-support\4.3.8.RELEASE\spring-context-support-4.3.8.RELEASE.jar;C:\Users\turbanov\.m2\repository\org\springframework\spring-core\4.3.8.RELEASE\spring-core-4.3.8.RELEASE.jar;C:\Users\turbanov\.m2\repository\org\springframework\spring-expression\4.3.8.RELEASE\spring-expression-4.3.8.RELEASE.jar;C:\Users\turbanov\.m2\repository\org\springframework\spring-jdbc\4.3.8.RELEASE\spring-jdbc-4.3.8.RELEASE.jar;C:\Users\turbanov\.m2\repository\org\springframework\spring-tx\4.3.8.RELEASE\spring-tx-4.3.8.RELEASE.jar;C:\Users\turbanov\.m2\repository\org\springframework\spring-instrument\4.3.8.RELEASE\spring-instrument-4.3.8.RELEASE.jar;D:\proj\common\profiler-compiler-plugin\target\classes;C:\Users\turbanov\.m2\repository\com\mchange\c3p0\0.9.5\c3p0-0.9.5.jar;C:\Users\turbanov\.m2\repository\com\mchange\mchange-commons-java\0.2.9\mchange-commons-java-0.2.9.jar;C:\Users\turbanov\.m2\repository\aopalliance\aopalliance\1.0\aopalliance-1.0.jar;C:\Users\turbanov\.m2\repository\org\aspectj\aspectjrt\1.8.13\aspectjrt-1.8.13.jar;C:\Users\turbanov\.m2\repository\org\aspectj\aspectjtools\1.8.13\aspectjtools-1.8.13.jar;C:\Users\turbanov\.m2\repository\org\aspectj\aspectjweaver\1.8.13\aspectjweaver-1.8.13.jar;C:\Users\turbanov\.m2\repository\commons-codec\commons-codec\1.7\commons-codec-1.7.jar;C:\Users\turbanov\.m2\repository\joda-time\joda-time\2.5\joda-time-2.5.jar;C:\Users\turbanov\.m2\repository\com\h2database\h2\1.4.196\h2-1.4.196.jar;C:\Users\turbanov\.m2\repository\com\devexperts\kilometrics\2\kilometrics-2.jar;C:\Users\turbanov\.m2\repository\io\dropwizard\metrics\metrics-core\3.1.0\metrics-core-3.1.0.jar;C:\Users\turbanov\.m2\repository\org\jctools\jctools-core\2.0\jctools-core-2.0.jar;C:\Users\turbanov\.m2\repository\org\slf4j\slf4j-api\1.7.25\slf4j-api-1.7.25.jar;D:\proj\server\configServer\target\classes -aspectpath C:\Users\turbanov\.m2\repository\org\springframework\spring-aspects\4.3.8.RELEASE\spring-aspects-4.3.8.RELEASE.jar;D:\proj\server\serverFoundation\target\classes -d D:\proj\server\configServer\target\classes -s D:\proj\server\configServer\target\generated-sources\aspectj-maven-plugin D:\proj\server\configServer\src\com\devexperts\dxcore\server\dxconfig\dao\ConfigurationBuilder.java D:\proj\server\configServer\src\com\devexperts\dxcore\server\dxconfig\dao\ConfigurationByteChunkMappingQuery.java D:\proj\server\configServer\src\com\devexperts\dxcore\server\dxconfig\dao\ConfigurationDAO.java D:\proj\server\configServer\src\com\devexperts\dxcore\server\dxconfig\dao\ConfigurationMappingQuery.java D:\proj\server\configServer\src\com\devexperts\dxcore\server\dxconfig\dao\ConfigurationsQuery.java D:\proj\server\configServer\src\com\devexperts\dxcore\server\dxconfig\dao\ConfigurationsSimpleQuery.java D:\proj\server\configServer\src\com\devexperts\dxcore\server\dxconfig\dao\ConfigurationStringChunkMappingQuery.java D:\proj\server\configServer\src\com\devexperts\dxcore\server\dxconfig\dao\DxConfigurationConnectionCustomizer.java D:\proj\server\configServer\src\com\devexperts\dxcore\server\dxconfig\LocalConfigurationCentral.java D:\proj\server\configServer\src\com\devexperts\dxcore\server\dxconfig\LocalDXCoreConfigFactory.java D:\proj\server\configServer\src\com\devexperts\dxcore\server\dxconfig\services\ConfigurationServiceImpl.java D:\proj\server\configServer\src\com\devexperts\dxcore\server\dxconfig\services\DxConfigAccessControlServiceImpl.java D:\proj\server\configServer\src\com\devexperts\dxcore\server\dxconfig\services\InternalConfigurationServiceImpl.java D:\proj\server\configServer\src\com\devexperts\dxcore\server\dxconfig\springconfig\datasource\DxConfigServerDataSourceBeans.java D:\proj\server\configServer\src\com\devexperts\dxcore\server\dxconfig\springconfig\shared\DxCoreDxConfigServerDxCoreCreationBeans.java D:\proj\server\configServer\src\com\devexperts\dxcore\server\dxconfig\springconfig\shared\DxCoreServerDxConfigBeans.java
[main] [DEBUG] Compiling and weaving 16 sources to D:\proj\server\configServer\target\classes
[main] [DEBUG] Arguments file written : D:\proj\server\configServer\target\classes\builddef.lst
[main] [INFO] Showing AJC message detail for messages of types: [error, warning, fail]
[main] [ERROR] can't determine superclass of missing type java.lang.Object
when batch building BuildConfig[null] #Files=16 AopXmls=#0
 [Xlint:cantFindType]
	<unknown source file>:<no line information>
[main] [ERROR] can't determine superclass of missing type java.lang.Object
when batch building BuildConfig[null] #Files=16 AopXmls=#0
 [Xlint:cantFindType]
	<unknown source file>:<no line information>
[main] [ERROR] can't determine superclass of missing type java.lang.Object
when batch building BuildConfig[null] #Files=16 AopXmls=#0
 [Xlint:cantFindType]
	<unknown source file>:<no line information>
[main] [ERROR] can't determine superclass of missing type java.lang.Object
when batch building BuildConfig[null] #Files=16 AopXmls=#0
 [Xlint:cantFindType]
	<unknown source file>:<no line information>
[main] [ERROR] can't determine superclass of missing type java.lang.Object
when batch building BuildConfig[null] #Files=16 AopXmls=#0
 [Xlint:cantFindType]
	<unknown source file>:<no line information>
[main] [ERROR] can't determine superclass of missing type java.lang.Object
when batch building BuildConfig[null] #Files=16 AopXmls=#0
 [Xlint:cantFindType]
	<unknown source file>:<no line information>
[main] [ERROR] can't determine superclass of missing type java.lang.Object
when batch building BuildConfig[null] #Files=16 AopXmls=#0
 [Xlint:cantFindType]
	<unknown source file>:<no line information>
[main] [ERROR] can't determine superclass of missing type java.lang.Object
when batch building BuildConfig[null] #Files=16 AopXmls=#0
 [Xlint:cantFindType]
	<unknown source file>:<no line information>
[main] [ERROR] can't determine superclass of missing type java.lang.Object
when batch building BuildConfig[null] #Files=16 AopXmls=#0
 [Xlint:cantFindType]
	<unknown source file>:<no line information>
[main] [DEBUG] deactivating aspect 'org.springframework.cache.aspectj.JCacheCacheAspect' as it requires type 'javax.cache.annotation.CacheResult' which cannot be found on the classpath
[main] [ERROR] can't determine superclass of missing type java.lang.Object
when batch building BuildConfig[null] #Files=16 AopXmls=#0
 [Xlint:cantFindType]
	<unknown source file>:<no line information>

Looks like need to wait for aspectj 1.9 release
https://www.eclipse.org/aspectj/

**Comment by davidkarlsen** [comment] 2018-02-11 15:23
Maybe you could test by adding aspectj 1.9.0 RC2 dependencies in the plugins dependencies section, like explained here: https://stackoverflow.com/questions/17422013/override-dependencies-in-a-maven-plugin-one-plugin-different-modules-and-diffe

**Comment by JamesPan** [comment] 2018-03-25 09:18
I just found an ugly trick to make aspectj working with Java 9, just point com.sun:tools to the pom.xml and the compiler just run.

```xml
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>aspectj-maven-plugin</artifactId>
    <version>1.11</version>
    <executions>
        <execution>
            <goals>
                <goal>compile</goal>
                <goal>test-compile</goal>
            </goals>
            <configuration>
                <source>1.8</source>
                <target>1.8</target>
                <complianceLevel>1.8</complianceLevel>
                <encoding>UTF-8</encoding>
                <verbose>true</verbose>
                <weaveDependencies>
                    <weaveDependency>
                        <groupId>io.grpc</groupId>
                        <artifactId>grpc-netty</artifactId>
                    </weaveDependency>
                </weaveDependencies>
                <showWeaveInfo>true</showWeaveInfo>
                <XnoInline>true</XnoInline>
            </configuration>
        </execution>
    </executions>
    <dependencies>
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjrt</artifactId>
            <version>1.9.0.RC2</version>
        </dependency>
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjtools</artifactId>
            <version>1.9.0.RC2</version>
        </dependency>
        <dependency>
            <groupId>com.sun</groupId>
            <artifactId>tools</artifactId>
            <version>${java.version}</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/pom.xml</systemPath>
        </dependency>
    </dependencies>
</plugin>
```

**Comment by turbanoff** [comment] 2018-04-19 09:52
aspectj 1.9.0 released - https://www.eclipse.org/aspectj/doc/released/README-190.html
Let's update dependencies

**Comment by davidkarlsen** [comment] 2018-04-19 10:46
@turbanoff only need one test to be fixed: https://github.com/mojohaus/aspectj-maven-plugin/pulls

**Comment by amiparikh2102** [comment] 2018-04-20 17:25
@JamesPan Why does this fix work? I can confirm that it worked for me, but I don't understand why.

**Comment by ctomc** [comment] 2018-05-15 11:18
Test was fixed in #37 as well as few other things.

**Comment by aiannucci** [comment] 2018-08-22 14:46
When can we have a 1.11.1 release? This keeps failing in Java 9/10

**Comment by m50d** [comment] 2018-09-06 12:38
@aiannucci I've published a build with these fixes to maven central as `com.github.m50d:aspectj-maven-plugin:1.11.1` for the time being.

**Comment by mpet** [comment] 2018-09-19 05:26
Hi We have forked the latest code base and we set the compliance level to 1.10.

We use the following  setting:

 ```
<aspectj.version>1.9.1</aspectj.version>
<aspectj.maven.plugin.version>1.11.1-FORK</aspectj.maven.plugin.version> 
 
```

And configure it with;

 ```
<plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>aspectj-maven-plugin</artifactId>
                <version>${aspectj.maven.plugin.version}</version>
                <configuration>
                    <complianceLevel>10</complianceLevel> <!--  should be changed to ${compiler.compliance.java.version} when the plugin support java 10. -->
                    <includes>
                        <include>**/*.java</include>
                        <include>**/*.aj</include>
                    </includes>
                    <aspectDirectory>src/main/aspect</aspectDirectory>
                    <testAspectDirectory>src/test/aspect</testAspectDirectory>
                    <XaddSerialVersionUID>true</XaddSerialVersionUID>
                    <showWeaveInfo>true</showWeaveInfo>
                </configuration>
                <executions>
                    <execution>
                        <id>compile_with_aspectj</id>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjrt</artifactId>
                        <version>${aspectj.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjtools</artifactId>
                        <version>${aspectj.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
```
 
Then when we run.

`mvn clean compile`

We get the following error for all classes and it fails:

> [ERROR] Type mismatch: cannot convert from element type Object to Map.Entry<String,Integer>
> 	/repo/emarald/dura-jcat/mje/resource-manager/src/main/java/com/ericsson/commonlibrary/resourcemanager/factory/DefaultLayer1NetworkServiceFactory.java:26
> for (Map.Entry<String, Integer> entry : resource.getLayer1SwitchToIndexMap().entrySet()) {
>                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 

Have anyone succeeded with using java 10 set at compliance level? Or do you have an idea of what the problem could be?

//mikael

**Comment by attempts-to-code** [comment] 2018-09-20 06:28
i'm wondering if we can have a release to fix the java version 9+ issues?

**Comment by AlphaUno1** [comment] 2021-02-22 11:37
> I tried to run version from repo. Got this strange error on java 9
> 
> > [main] [ERROR] Failed to execute goal org.codehaus.mojo:aspectj-maven-plugin:1.11.0_2018_02_11:compile (default) on project dxAuthServer: AJC compiler errors:
> > [main] [ERROR] error can't determine superclass of missing type java.lang.Object
> > [main] [ERROR] when batch building BuildConfig[null] #Files=57 AopXmls=#0
> > [main] [ERROR]  [Xlint:cantFindType]
> > [main] [ERROR] error can't determine superclass of missing type java.lang.Object
> > [main] [ERROR] when batch building BuildConfig[null] #Files=57 AopXmls=#0
> > [main] [ERROR]  [Xlint:cantFindType]
> > [main] [ERROR] error can't determine superclass of missing type java.lang.Object
> > [main] [ERROR] when batch building BuildConfig[null] #Files=57 AopXmls=#0
> > [main] [ERROR]  [Xlint:cantFindType]
> > [main] [ERROR] error can't determine superclass of missing type java.lang.Object
> > [main] [ERROR] when batch building BuildConfig[null] #Files=57 AopXmls=#0
> > [main] [ERROR]  [Xlint:cantFindType]
> > [main] [ERROR] error can't determine superclass of missing type java.lang.Object
> > [main] [ERROR] when batch building BuildConfig[null] #Files=57 AopXmls=#0
> > [main] [ERROR]  [Xlint:cantFindType]
> > [main] [ERROR] error can't determine superclass of missing type java.lang.Object
> > [main] [ERROR] when batch building BuildConfig[null] #Files=57 AopXmls=#0
> > [main] [ERROR]  [Xlint:cantFindType]
> > [main] [ERROR] error can't determine superclass of missing type java.lang.Object
> > [main] [ERROR] when batch building BuildConfig[null] #Files=57 AopXmls=#0
> > [main] [ERROR]  [Xlint:cantFindType]
> > [main] [ERROR] error can't determine superclass of missing type java.lang.Object
> > [main] [ERROR] when batch building BuildConfig[null] #Files=57 AopXmls=#0
> > [main] [ERROR]  [Xlint:cantFindType]
> > [main] [ERROR] error can't determine superclass of missing type java.lang.Object
> > [main] [ERROR] when batch building BuildConfig[null] #Files=57 AopXmls=#0
> > [main] [ERROR]  [Xlint:cantFindType]
> > [main] [ERROR] error can't determine superclass of missing type java.lang.Object
> > [main] [ERROR] when batch building BuildConfig[null] #Files=57 AopXmls=#0
> > [main] [ERROR]  [Xlint:cantFindType]
> > [main] [ERROR] error can't determine superclass of missing type java.lang.Object
> > [main] [ERROR] when batch building BuildConfig[null] #Files=57 AopXmls=#0
> > [main] [ERROR]  [Xlint:cantFindType]
> > [main] [ERROR] error can't determine superclass of missing type java.lang.Object
> > [main] [ERROR] when batch building BuildConfig[null] #Files=57 AopXmls=#0
> > [main] [ERROR]  [Xlint:cantFindType]
> > [main] [ERROR] error can't determine superclass of missing type java.lang.Object
> > [main] [ERROR] when batch building BuildConfig[null] #Files=57 AopXmls=#0
> > [main] [ERROR]  [Xlint:cantFindType]

I fixed these errors by refactoring (just changing the name). You can also try to reinstall AspectJ. They occurred as I needed to get Netbeans working on the same system and some delete/reinstall caused it to lose site of the superclass.

**Comment by bmarwell** [comment] 2021-05-30 21:15
Fixed in https://github.com/mojohaus/aspectj-maven-plugin/commit/fced312e8c5900c655999d171f1024f25b298415

**Closed by bmarwell** 2021-05-30 21:15 UTC
Labels: enhancement
